esphome:
  name: node
  friendly_name: node
  on_boot:
    priority: 800
    then:
      - wait_until: 
          wifi.connected:
      - button.press: "start_server"

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  reboot_timeout: 0s
  encryption:
    key: "15mZM0ZuAK37G6ENLbqy+JHn/01+Atw2Wj8Tf/lkAs8="

ota:
  password: "132e200f5d473b72b43b946abaa3313d"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  reboot_timeout: 0s

  manual_ip:
    static_ip: 192.168.0.141
    gateway: 192.168.0.1
    subnet: 255.255.255.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Node Fallback Hotspot"
    password: "eJRpCcADg6vr"
  

captive_portal:

# HA Server
button:
  - platform: wake_on_lan
    id: "start_server"
    name: "Start the Server"
    target_mac_address: 04:7d:7b:42:f0:61

output:
#   - platform: gpio
#     id: "switch_1"
#     pin: 14
#     inverted: True
#   - platform: gpio
#     id: "switch_2"
#     pin: 27
#     inverted: True
  - platform: gpio
    id: "switch_3"
    pin: 33
    inverted: True
  - platform: gpio
    id: "switch_4"
    pin: 25
    inverted: True
  - platform: gpio
    id: "switch_5"
    pin: 26
    inverted: True
  - platform: gpio
    id: "switch_6"
    pin: 27
    inverted: True
  - platform: gpio
    id: "switch_7"
    pin: 14
    inverted: True
  - platform: gpio
    id: "switch_8"
    pin: 32
    inverted: True

light:
#   - platform: binary
#     id: "light_1"
#     name: "Light 1"
#     output: "switch_1"
#   - platform: binary
#     id: "light_2"
#     name: "Light 2"
#     output: "switch_2"
  - platform: binary
    id: "left"
    name: "Left"
    output: "switch_3"
    restore_mode: RESTORE_DEFAULT_OFF
  - platform: binary
    id: "outside_left"
    name: "Outside Left"
    output: "switch_4"
    restore_mode: RESTORE_DEFAULT_OFF
  - platform: binary
    id: "right"
    name: "Right"
    output: "switch_5"
    restore_mode: RESTORE_DEFAULT_OFF
  - platform: binary
    id: "yellow"
    name: "Yellow"
    output: "switch_6"
    restore_mode: RESTORE_DEFAULT_OFF
  - platform: binary
    id: "outside_front"
    name: "Outside Front"
    output: "switch_7"
    restore_mode: RESTORE_DEFAULT_OFF

fan:
  - platform: binary
    id: "fan_1"
    name: "Fan"
    output: "switch_8"
    restore_mode: RESTORE_DEFAULT_OFF

binary_sensor:
#   - platform: gpio
#     name: "Switch 1"
#     pin:
#       number: 15
#       inverted: True
#       mode:
#         input: True
#         pulldown: True
#     filters:
#       - delayed_off: 50ms
#     on_press:
#       then:
#         - light.toggle: "light_1"
#     on_release:
#       then:
#         - light.toggle: "light_1"
#   - platform: gpio
#     name: "Switch 2"
#     pin:
#       number: 2
#       inverted: True
#       mode:
#         input: True
#         pulldown: True
#     filters:
#       - delayed_off: 50ms
#     on_press:
#       then:
#         - light.toggle: "light_2"
#     on_release:
#       then:
#         - light.toggle: "light_2"
  - platform: gpio
    name: "Switch 3"
    pin:
      number: 21
      mode:
        input: True
        pulldown: True
    filters:
      - delayed_off: 50ms
    on_press:
      then:
        - light.toggle: "left"
    on_release:
      then:
        - light.toggle: "left"
  - platform: gpio
    name: "Switch 4"
    pin:
      number: 5
      mode:
        input: True
        pulldown: True
    filters:
      - delayed_off: 50ms
    on_press:
      then:
        - light.toggle: "outside_left"
    on_release:
      then:
        - light.toggle: "outside_left"
  - platform: gpio
    name: "Switch 5"
    pin:
      number: 17
      mode:
        input: True
        pulldown: True
    filters:
      - delayed_off: 50ms
    on_press:
      then:
        - light.toggle: "right"
    on_release:
      then:
        - light.toggle: "right"
  - platform: gpio
    name: "Switch 6"
    pin:
      number: 16
      mode:
        input: True
        pulldown: True
    filters:
      - delayed_off: 50ms
    on_press:
      then:
        - light.toggle: "outside_front"
    on_release:
      then:
        - light.toggle: "outside_front"
  - platform: gpio
    name: "Switch 7"
    pin:
      number: 2
      mode:
        input: True
        pulldown: True
    filters:
      - delayed_off: 50ms
    on_press:
      then:
        - light.toggle: "right"
    on_release:
      then:
        - light.toggle: "right"
  - platform: gpio
    name: "Switch 8"
    pin:
      number: 15
      mode:
        input: True
        pulldown: True
    filters:
      - delayed_off: 50ms
    on_press:
      then:
        - fan.toggle: "fan_1"
    on_release:
      then:
        - fan.toggle: "fan_1"
