# Example configuration.yaml entry
homeassistant:
  media_dirs:
    media: /config/media
    snapshots: /config/image/snapshots
  allowlist_external_dirs:
    - /config/image/snapshots
    - /tmp

http:
  ip_ban_enabled: true
  login_attempts_threshold: 5
  use_x_forwarded_for: true
  trusted_proxies:
    - 192.168.0.161
    # Cloudflare proxies
    - 173.245.48.0/20
    - 103.21.244.0/22
    - 103.22.200.0/22
    - 103.31.4.0/22
    - 141.101.64.0/18
    - 108.162.192.0/18
    - 190.93.240.0/20
    - 188.114.96.0/20
    - 197.234.240.0/22
    - 198.41.128.0/17
    - 162.158.0.0/15
    - 104.16.0.0/13
    - 104.24.0.0/14
    - 172.64.0.0/13
    - 131.0.72.0/22

device_tracker:
  - platform: tenda_tracker
    host: 192.168.0.1
    password: !secret tenda_password
    interval_seconds: 10
    consider_home: 180
    new_device_defaults:
    track_new_devices: true

sensor:
  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /config
      - type: memory_use_percent
      - type: processor_use
      - type: processor_temperature
      - type: last_boot

google_assistant:
  project_id: homeassistant-7470
  service_account: !include SERVICE_ACCOUNT.JSON
  report_state: true

panel_iframe:
  portainer:
    title: "Portainer"
    url: "http://192.168.0.161:9000/#/containers"
    icon: mdi:docker
    require_admin: true

  esphome:
    title: "ESPHome"
    url: "http://192.168.0.161:6052"
    icon: mdi:chip
    require_admin: true

notify:
  - platform: html5
    vapid_pub_key: YOUR_PUBLIC_KEY
    vapid_prv_key: YOUR_PRIVATE_KEY
    vapid_email: YOUR_EMAIL

# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
